project:
  type: website
  output-dir: docs

website:
  title: "Sudarshan A. Shetty"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications 
      - href: software.qmd
        text: Software and Resources 

format:
  html:
    theme: sandstone 
    css: styles.css
    toc: true

editor: visual   

