---
title: ""
---
  

-------------------
  
**Organization/Event management experience**  

*Wageningen University and research*  	

•	Autumn 2017	Organized the SIAM Symposium 2017  

•	Spring 2018	Open & Reproducible Microbiome Data Analysis Spring School (https://goo.gl/xtwmAH)   

Note: *The microbiomeutilities-shiny application was used for interactive introdution to microbial community data analysis.  

  
**Grants and Awards**  
• FEMS travel grant 2016
• ISME young investigator travel grant 2018  

**Workshops/Summer Schools**  
•	Summer School on Ecological Network Inference & Analysis. KU Leuven, Belgium (2017).  
•	Summer School in Biomedical Research and Public Health: Microbial Genomics & Metagenomics Workshop. FISABIO, Valencia (2016).  
•	Second International Next Generation Sequencing Data Analysis Workshop organized by Persistent Systems Ltd. at Pune, Maharashtra, India (2012).  

**Open data and resources**   
•	Shetty SA & Lahti L (2018). A list of R environment based tools for 16S rRNA gene data exploration, statistical analysis and visualization (Version v1.0). Zenodo. http://doi.org/10.5281/zenodo.1256879.  
•	Shetty SA, Lahti L, Hermes Gerben DA, & Smidt H. (2018, September 27). Microbial bioinformatics introductory course material 2018 (Version 0.01). Zenodo. http://doi.org/10.5281/zenodo.1436630.  
•	GitHub repositories: https://github.com/microsud?tab=repositories.     




<p>Copyright &copy; 2020 Sudarshan A. Shetty. All rights reserved.</p>

