---
title: "Research"
---


**Ecophysiology of Core Human Intestinal Bacteria**  
In this project, we aim to understand the physiology and role of the core bacteria that have been identified by us. We use basic anaerobic microbiology techniques supported by genomics, proteomics and may be also transcriptomics. The goal here is to better understand these microbes before they can be used to next generation of therapeutic. For more details please click on the [link](https://academic.oup.com/femsre/article-lookup/doi/10.1093/femsre/fuw045) to check the publication for a list of interesting core bacteria in human gut.    


**Towards minimal microbiome**  
In this study, we aim to study ecological and physiological dynamics of key bacterial strains in defined microbial communities. We also aim to address challenges in data acquisition, integration and visualization in such studies. The combination of multi-omics and basic anaerobic physiology is expected to give crucial insights into the resilience, stability and functional networks under well defined growth condtions.   
For more details please check our review [Reconstructing functional networks in the human intestinal tract using synthetic microbiomes](https://www.sciencedirect.com/science/article/pii/S0958166918302301).  

---------


**Research Experience**   

* March 2019 - Present  
Post Doctoral Researcher at Laboratory of Microbiology, Wageningen University and Research.  
•	Design and development of synthetic human gut microbiomes.  
•	Developing multi-omics integrative biodiscovery pipelines for efficient utilization of synthetic microbiomes in a variety of biotech applications.  

* August 2014 - March 2019  	  
PhD, Laboratory of Microbiology, Wageningen University and Research.  
•	Used a combination of genomics, proteomics and anaerobic culturing to elucidate the physiology of core human intestinal bacteria.  
•	Used a combination of in-silico and in-vitro approach to develop a defined consortium of human intestinal microbiome.  
•	Developed analytical pipelines in R for high-throughput sequencing data (primarily 16S rRNA gene amplicon).    

* June 2012 - June 2014	 	
Junior Research Fellow, National Centre for Cell Science.  
•	Developed 48-well plate screening method for bio-molecules from bacteria isolated from various ecological niches of Western Ghats.  
•	Genome sequencing and analysis of potential novel anaerobic bacteria isolated from feces of healthy human subjects.  
•	High-throughput sequencing and data analysis of microbial community in human subjects with different dietary habits (The Pune Microbiome Study).  
