---
title: "Science communication"
---

**Scientific Conferences**  

*Conference Presentations (Oral)*
•	Shetty SA, Lahti L, Smidt H, de Vos WM. Unravelling the ecophysiological dynamics of core human intestinal bacteria in a defined consortium. International Conference on Microbiome Research (ICMR) 2018, India.(Best oral presentation award)  
•	Shetty SA, Hugenholtz F, Lahti L, Smidt H, de Vos WM. Intestinal microbiome landscape of Western adults - Phylogenetic core and its functionality. INRA-Rowett 2016, Clermont-Ferrand, France.  
•	Shetty SA, Bui TP, Lagkouvardos I, Ritari J, Chamlagain B, Douillard FP, Paulin L, Piironen V, Clavel T, Plugge CM, de Vos WM. Comparative genomics of Intestinimonas butyriciproducens, a lysine utilizing and butyrate producing bacteria in the human gut. The Netherlands Microbiology society (KNVM & NVMM) 2016.  
•	Shetty SA, Dhotre DP, Bhatia K, Verma AK, Mishra A, Ahuja V, Makharia GK, Shouche YS. Ultra-deep high-throughput sequencing of intestinal microbiota in celiac disease and first-degree relatives and effect of gluten free diet on them. The 54th Annual conference of Indian Society of Gastroenterology conference 2013.   

**General**   
Blog Author at Gut Microbiota for Health, created by the Gut Microbiota and Health Section of the European Society for Neurogastroenterology & Motility (ESNM), member of United European Gastroenterology (UEG).   
* Is Blastocystis a pathobiont? Prevalence data and beyond.   
* The Indian tribal gut microbiota unraveled.   
* Blastocystis —a possible pathobiont— linked with greater bacterial diversity.   

Twitter: [gutmicrobe](https://twitter.com/?lang=en)   

