---
title: "Open source tools and resources"
---


  

<div class="column-left">  
</div> 


1. **Phyloseq-based tools**
   * **microbiome R package**  
   Lahti L, Shetty SA, Blake T and Salojarvi J. (Bioconductor) [An R package for microbial community analysis](https://doi.org/doi:10.18129/B9.bioc.microbiome).  
   Tutorials can be found [here](https://microbiome.github.io/tutorials/).  
   
   * **microbiomeutilities**  
   Shetty SA, Lahti L. (GitHub) [Extending and supporting R package based on microbiome and phyloseq.](https://github.com/microsud/microbiomeutilities)   
   A utility package for the parent _microbiome_ R package. Tutorial can be found [here](https://microsud.github.io/microbiomeutilities/)   

   * **chkMocks**  
   Shetty SA. (GitHub) [chkMocks is a basic R package for comparing experimental mock communities (positive controls) with theoretical (expected) composition](https://microsud.github.io/chkMocks/)    
   
   * **syncomR**   
   [Analysis of Synthetic Microbial Communities.](https://github.com/microsud/syncomR)   
   Handling microbial community (MC) data with special emphasis on time series data from synthetic MCs. Bundles R
   codes openly available in literature into functions for convenient access.   


2. **TreeSummarizedExperiment-based tools**     
   * **microbiomeDataSets**  
   Ernst F, Lahti L, Shetty S (2021). [microbiomeDataSets: Experiment Hub based microbiome datasets](https://www.bioconductor.org/packages/devel/data/experiment/html/microbiomeDataSets.html).  
   _microbiomeDataSets_ is a collection of microbiome datasets loaded from Bioconductor's ExperimentHub infrastructure.  

   * **mia**  
   Ernst F, Shetty S, Borman T, Lahti L (2021). [mia: Microbiome analysis](https://www.bioconductor.org/packages/devel/bioc/html/mia.html)  
   _mia_ implements tools for microbiome analysis based on the SummarizedExperiment, SingleCellExperiment and TreeSummarizedExperiment infrastructure.   

More information on our efforts on expanding the the [R/Bioc microbiome ecosystem with SummarizedExperiment](https://microbiome.github.io/)  

---------   

#### **Training**    

<div class="column-left">  
</div>  

•	**microbiomeutilities-shiny**   
Shetty SA, Lahti L. (GitHub)  
[A web based shiny dashboard for prelimanry analysis of microbial census data.](https://gutmicrobe.shinyapps.io/microbiomeutils-shiny/)   
This shiny app is used for teaching basic 16S rRNA gene based microbial community analysis.  

•	**TeachingMIB20306**   
Shetty SA. (GitHub)  
[A web based shiny dashboard for proteomics data analysis.](https://github.com/microsud/TeachingMIB20306)   
Teaching MIB20306: This dashboard uses data from Bui, Thi Phuong Nam, Jarmo Ritari, Sjef Boeren, Pieter De Waard, Caroline M. Plugge, and Willem M. De Vos. ["Production of butyrate from lysine and the Amadori product fructoselysine by a human gut commensal." Nature Communications 6 (2015): 10062](https://www.nature.com/articles/ncomms10062). The data has been modified/subsetted for teaching purpose.    

---------   

#### **Open data and resources**     

<div class="column-left">  
</div> 

•	Lahti L, Shetty SA, Ernst F (2021)  [Orchestrating Microbiome Analysis](https://microbiome.github.io/OMA/)  

•	Shetty SA & Lahti L (2018). [A list of R environment based tools for 16S rRNA gene data exploration, statistical analysis and visualization](https://microsud.github.io/Tools-Microbiome-Analysis/) Zenodo. http://doi.org/10.5281/zenodo.1256879.  

•	Shetty SA, Lahti L, Hermes Gerben DA, & Smidt H. (2018, September 27). Microbial bioinformatics introductory course material 2018 (Version 0.01). Zenodo. http://doi.org/10.5281/zenodo.1436630.   

•	GitHub repositories: https://github.com/microsud?tab=repositories.     

---------   

#### **In development**     

<div class="column-left">  
</div> 

**RIVM-Microbiome-Toolbox**  
Tools for supporting reproducible microbiome data analysis at RIVM [more information](https://github.com/RIVM-IIV-Microbiome/biomeUtils)  

---------  
<div class="column-left">  
</div> 

<p>Copyright &copy; 2021 Sudarshan Shetty. All rights reserved.</p>

